/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef KOTLIN_CPP_LIB_H
#define KOTLIN_CPP_LIB_H

#ifdef _WIN32
#define KOTLIN_CPP_LIB_EXPORT_FUNC __declspec(dllexport)
#else
#define KOTLIN_CPP_LIB_EXPORT_FUNC
#endif

#include <string>

namespace kotlin_cpp_lib {
    class Greeter {
        public:
        std::string KOTLIN_CPP_LIB_EXPORT_FUNC greeting();
    };
}

#endif
