/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "kotlin-cpp-lib.h"

std::string kotlin_cpp_lib::Greeter::greeting() {
    return std::string("Hello, World!");
}
